exp_name: exps/planning
debug: false

log_every: 1
visualize_k: 1

# 2 fingers pinch
# pretrained_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/aug_on_the_fly_hand_obj_sampling_augment/train_tb_logs/aug_on_the_fly_hand_obj_sampling_augment/version_13/checkpoints/epoch=217-step=23980-val_loss=0.00760.ckpt"
# dynamics_config_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/aug_on_the_fly_hand_obj_sampling_augment/train_tb_logs/aug_on_the_fly_hand_obj_sampling_augment/version_13/hparams.yaml"

# palm pressing
# pretrained_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/palm_pressing/train_tb_logs/palm_pressing/version_1/checkpoints/epoch=258-step=20979-val_loss=0.00630.ckpt"
# dynamics_config_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/palm_pressing/train_tb_logs/palm_pressing/version_1/hparams.yaml"

# thumb pressing
# pretrained_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/thumb_press/train_tb_logs/thumb_press/version_0/checkpoints/epoch=232-step=18873-val_loss=0.00502.ckpt"
# dynamics_config_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/thumb_press/train_tb_logs/thumb_press/version_0/hparams.yaml"

# thumb pinching
# pretrained_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/thumb_pinch/train_tb_logs/thumb_pinch/version_0/checkpoints/epoch=217-step=14824-val_loss=0.00719.ckpt"
# dynamics_config_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/thumb_pinch/train_tb_logs/thumb_pinch/version_0/hparams.yaml"

# all skills
pretrained_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/all_skills/train_tb_logs/all_skills/version_0/checkpoints/epoch=282-step=96220-val_loss=0.00523.ckpt"
dynamics_config_path: "/home/coolbot/Documents/git/dex-dynamics/dynamics/exps/all_skills/train_tb_logs/all_skills/version_0/hparams.yaml"

horizon: 1
num_skills_per_sample: 6 # 1
# history_len: 30

real_world: False

test_batch_size: 1

num_execution_iterations: 1 # 30
num_samples: 2000 # 200
num_z_rotations: 8 # 16
num_skills_in_sequence: 2
sample_batch_size: 20
beta: 0.3
gamma: 1.0

update_std: False

SKILLS:
  - 2_fingers_pinching
  - palm_pressing
  # - thumb_pressing
  # - thumb_pinching

robot_type: "ability_hand_right" # "ability_hand_right"
robots:
  ability_hand_right:
    init_std:
      2_fingers_pinching:
        [
          0.0, 0.0, 0.0,  # wrist position
          0., 0., 0.,   # wrist orientation
          0., 0.2, 0., 0., 0., 0.2    # hand joint angles
        ]
      palm_pressing:
        [
          0.0, 0.0, 0.03,  # wrist position
          0., 0., 0.,   # wrist orientation
          0., 0., 0., 0., 0., 0.    # hand joint angles
        ]
      thumb_pressing:
        [
          0.0, 0.0, 0.03,  # wrist position
          0., 0., 0.,   # wrist orientation
          0., 0., 0., 0., 0., 0.    # hand joint angles
        ]
      thumb_pinching:
        [
          0.0, 0.0, 0.0,  # wrist position
          0., 0., 0.,   # wrist orientation
          0., 0., 0., 0., 0., 0.2    # hand joint angles
        ]
    init_action:
      2_fingers_pinching:
        [
          0.06, -0.02, -0.1,
          0, -50, 0, 
          -1.4, 0.4, 0, 0, 0, 0.35
        ] # heuristic setting for initial hand pose
      palm_pressing:
        [
          0.06, -0.02, -0.05,
          0, -90, 0, 
          0., 0, 0, 0, 0, 0.
        ] # heuristic setting for initial hand pose
      thumb_pressing:
        [
          0.0, 0.08, -0.15,
          90, 0, 0, 
          0, 0, 0, 0, 0, 0.
        ] # hand joint angles
      thumb_pinching:
        [
          0.06, -0.02, -0.1,
          0, -50, 0,
          -1.4, 0.4, 0.4, 0.4, 0.4, 0.35
        ] # heuristic setting for initial hand pose
    action_dim: 12
  xhand_right:
    action_dim: 18
    init_std: [
                0.0, 0.0, 0.0,  # wrist position
                0., 0., 0.0,   # wrist orientation
                0.1, 0, 0., 0., 0., 0.2, 0.2, 0, 0., 0., 0., 0.  # hand joint angles
              ]
    init_action: [
                  0.04, -0.02, -0.12, # x, y, z
                  110, 0, 90, # roll, pitch, yaw
                  1.4, 0, 0, 0, 0, 0.1, 1.3, 0, 0, 0, 0, 0
                ] # hand joint angles

loss:
  names: ["pointcloud"]
  weights: [10.]
  last_states: [0, 0, 0, 0, 0, 0, 0]
  eval: "pointcloud"
  radius: 0.01
  decay_factor: 0.99
  penetration_weight: 0.5 # 0.5 #  2
  attraction_weight: 0.5 #0.05
  penetration_threshold: -0.02


# goal_offset: [0, 0, 0.15]

# mesh: ""

# goal: 
#   position: [0.5, -0.2, 0.025]
#   orientation: [0, 0, 0]
# use_visual_feedback: true
# replan_sampler_params: 
#   mean: [0, 0, 0]
#   std: [0.00718885, 0.011, 0.000]
#   num_samples: 100
#   num_iterations: 1
#   gamma: 100
#   num_repeat: 1
#   horizon: 30
#   beta: 0.2

# initial_sampler_params: 
#   mean: [0, 0, 0]
#   old_std: [0.01418885, 0.022, 0.000]
#   std: [0.03, 0.03, 0.000]
#   num_samples: 500
#   num_iterations: 5
#   gamma: 100
#   num_repeat: 5
#   horizon: 30
#   beta: 0.3